<?php
/**
 * Magento
 */
?>
<label for="<?php echo $this->getFieldId('activity')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->__('Activity') ?></label>
<div class="input-box">
    <select id="<?php echo $this->getFieldId('activity')?>" name="<?php echo $this->getFieldName('activity')?>" title="<?php echo $this->__('Activity') ?>"<?php if ($this->isRequired()):?> class="validate-select"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
        <?php $options = Mage::getResourceSingleton('customer/customer')->getAttribute('activity')->getSource()->getAllOptions();?>
        <?php $value = $this->getActivity();?>
        <?php foreach ($options as $option):?>
            <option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
        <?php endforeach;?>
    </select>
</div>
